/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_position_free: (a: number, b: number) => void;
export const position_get_piece_at: (a: number, b: number, c: number) => [number, number];
export const position_is_white_turn: (a: number) => number;
export const position_piece_count: (a: number) => number;
export const __wbg_searchresult_free: (a: number, b: number) => void;
export const count_legal_moves: (a: number) => number;
export const engine_info: () => [number, number];
export const eval_position: (a: number) => number;
export const from_fen: (a: number, b: number) => [number, number, number];
export const get_best_move: (a: number, b: number) => [number, number];
export const get_best_move_iterative: (a: number, b: number) => [number, number];
export const get_legal_moves: (a: number) => [number, number];
export const get_pseudo_legal_moves: (a: number) => [number, number];
export const is_in_check: (a: number) => number;
export const make_move: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const make_move_uci: (a: number, b: number, c: number) => number;
export const new_game: () => number;
export const ping: () => [number, number];
export const run_perft: (a: number, b: number) => bigint;
export const search_position: (a: number, b: number) => number;
export const searchresult_best_move: (a: number) => [number, number];
export const searchresult_depth: (a: number) => number;
export const searchresult_nodes: (a: number) => bigint;
export const searchresult_score: (a: number) => number;
export const to_fen: (a: number) => [number, number];
export const init: () => void;
export const __wbg_castlingrights_free: (a: number, b: number) => void;
export const __wbg_get_castlingrights_0: (a: number) => number;
export const __wbg_get_move_0: (a: number) => number;
export const __wbg_move_free: (a: number, b: number) => void;
export const __wbg_set_castlingrights_0: (a: number, b: number) => void;
export const __wbg_set_move_0: (a: number, b: number) => void;
export const __wbg_square_free: (a: number, b: number) => void;
export const __wbg_get_square_0: (a: number) => number;
export const __wbg_set_square_0: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
